version: '3'
services:
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./:/fluent-bit/etc/
    # command:
    #   - /fluent-bit/bin/fluent-bit -p script=filters.lua -c /fluent-bit/etc/fluent-bit.conf
 
  flog:
    image: mingrammer/flog
    depends_on:
      - fluent-bit
    command: '-l'
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
        tag: apache        

  # nginx:
  #   image: kscarlett/nginx-log-generator
  #   depends_on:
  #     - fluent-bit
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-async-connect: "true"
  #       fluentd-retry-wait: 1s
  #       fluentd-max-retries: 30
  #       tag: nginx